// Generated 22 Oct 2021 08:34 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.AccountType
{
    [Serializable]
    public class AccountTypeList
     : SingularBusinessListBase<AccountTypeList, AccountType>
    {
        #region " Business Methods "

        public AccountType GetItem(int AccountTypeID)
        {
            foreach (AccountType child in this)
            {
                if (child.AccountTypeID == AccountTypeID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Account Types";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }
            public int userID { get; set; }
            
        }

        public static AccountTypeList NewAccountTypeList()
        {
            return new AccountTypeList();
        }

        public AccountTypeList()
        {
            // must have parameter-less constructor
        }

        public static AccountTypeList GetAccountTypeList(int userID)
        {
            return DataPortal.Fetch<AccountTypeList>(new Criteria() {userID = userID });
        }
        

        public static AccountTypeList GetAccountTypeList()
        {
            return DataPortal.Fetch<AccountTypeList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(AccountType.GetAccountType(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getAccountTypeList";
                        cm.Parameters.AddWithValue("@UserID", Singular.Security.Security.CurrentIdentity.UserID);
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}