// Generated 11 Nov 2021 09:22 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Carts
{
    [Serializable]
    public class CheckOut
     : SingularBusinessBase<CheckOut>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> CheckOutIDProperty = RegisterProperty<int>(c => c.CheckOutID, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int CheckOutID
        {
            get { return GetProperty(CheckOutIDProperty); }
        }

        public static PropertyInfo<int> UserIDProperty = RegisterProperty<int>(c => c.UserID, "User", 0);
        /// <summary>
        /// Gets and sets the User value
        /// </summary>
        [Display(Name = "User", Description = ""),
        Required(ErrorMessage = "User required")]
        public int UserID
        {
            get { return GetProperty(UserIDProperty); }
            set { SetProperty(UserIDProperty, value); }
        }

        public static PropertyInfo<Decimal> TotalPriceProperty = RegisterProperty<Decimal>(c => c.TotalPrice, "Total Price", 0D);
        /// <summary>
        /// Gets and sets the Total Price value
        /// </summary>
        [Display(Name = "Total Price", Description = ""),
        Required(ErrorMessage = "Total Price required")]
        public Decimal TotalPrice
        {
            get { return GetProperty(TotalPriceProperty); }
            set { SetProperty(TotalPriceProperty, value); }
        }

        public static PropertyInfo<Decimal> TempBalanceProperty = RegisterProperty<Decimal>(c => c.TempBalance, "Temp Balance", 0D);
        /// <summary>
        /// Gets and sets the Temp Balance value
        /// </summary>
        [Display(Name = "Temp Balance", Description = ""),
        Required(ErrorMessage = "Temp Balance required")]
        public Decimal TempBalance
        {
            get { return GetProperty(TempBalanceProperty); }
            set { SetProperty(TempBalanceProperty, value); }
        }

        public static PropertyInfo<DateTime> CheckoutDateProperty = RegisterProperty<DateTime>(c => c.CheckoutDate, "Checkout Date");
        /// <summary>
        /// Gets and sets the Checkout Date value
        /// </summary>
        [Display(Name = "Checkout Date", Description = ""),
        Required(ErrorMessage = "Checkout Date required")]
        public DateTime CheckoutDate
        {
            get
            {
                return GetProperty(CheckoutDateProperty);
            }
            set
            {
                SetProperty(CheckoutDateProperty, value);
            }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(CheckOutIDProperty);
        }

        public override string ToString()
        {
            if (this.CheckOutID.ToString().Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "Check Out");
                }
                else
                {
                    return String.Format("Blank {0}", "Check Out");
                }
            }
            else
            {
                return this.CheckOutID.ToString();
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewCheckOut() method.
        }

        public static CheckOut NewCheckOut()
        {
            return DataPortal.CreateChild<CheckOut>();
        }

        public CheckOut()
        {
            MarkAsChild();
        }

        internal static CheckOut GetCheckOut(SafeDataReader dr)
        {
            var c = new CheckOut();
            c.Fetch(dr);
            return c;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(CheckOutIDProperty, sdr.GetInt32(i++));
                LoadProperty(UserIDProperty, sdr.GetInt32(i++));
                LoadProperty(TotalPriceProperty, sdr.GetDecimal(i++));
                LoadProperty(TempBalanceProperty, sdr.GetDecimal(i++));
                LoadProperty(CheckoutDateProperty, sdr.GetValue(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            AddPrimaryKeyParam(cm, CheckOutIDProperty);

            cm.Parameters.AddWithValue("@UserID", GetProperty(UserIDProperty));
            cm.Parameters.AddWithValue("@TotalPrice", GetProperty(TotalPriceProperty));
            cm.Parameters.AddWithValue("@TempBalance", GetProperty(TempBalanceProperty));
            cm.Parameters.AddWithValue("@CheckoutDate", CheckoutDate);

            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(CheckOutIDProperty, scm.Parameters["@CheckOutID"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@CheckOutID", GetProperty(CheckOutIDProperty));
        }

        #endregion

    }

}