// Generated 11 Nov 2021 09:22 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Carts
{
    [Serializable]
    public class CheckOutList
     : SingularBusinessListBase<CheckOutList, CheckOut>
    {
        #region " Business Methods "

        public CheckOut GetItem(int CheckOutID)
        {
            foreach (CheckOut child in this)
            {
                if (child.CheckOutID == CheckOutID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Check Outs";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static CheckOutList NewCheckOutList()
        {
            return new CheckOutList();
        }

        public CheckOutList()
        {
            // must have parameter-less constructor
        }

        public static CheckOutList GetCheckOutList()
        {
            return DataPortal.Fetch<CheckOutList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(CheckOut.GetCheckOut(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getCheckOutList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}