// Generated 26 Oct 2021 14:51 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MEWeb.ROSubCategories
{
    [Serializable]
    public class SubCategoryList
     : SingularReadOnlyListBase<SubCategoryList, ROSubCategory>
    {
        #region " Business Methods "

        public ROSubCategory GetItem(int SubCategoryID)
        {
            foreach (ROSubCategory child in this)
            {
                if (child.SubCategoryID == SubCategoryID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Sub Categorys";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static ROSubCategoryList NewROSubCategoryList()
        {
            return new ROSubCategoryList();
        }

        public SubCategoryList()
        {
            // must have parameter-less constructor
        }

        public static ROSubCategoryList GetROSubCategoryList()
        {
            return DataPortal.Fetch<ROSubCategoryList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            this.IsReadOnly = false;
            while (sdr.Read())
            {
                this.Add(ROSubCategory.GetROSubCategory(sdr));
            }
            this.IsReadOnly = true;
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getROSubCategoryList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

    public class ROSubCategoryList
    {
    }
}