// Generated 16 Nov 2021 11:23 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Products
{
    [Serializable]
    public class DeliveryList
     : SingularBusinessListBase<DeliveryList, Delivery>
    {
        #region " Business Methods "

        public Delivery GetItem(int DeliveryID)
        {
            foreach (Delivery child in this)
            {
                if (child.DeliveryID == DeliveryID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Deliverys";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }
            public int? UserID = null;
            public int? ProductID = null;
            public int? DeliveryTypeID = null;
        }

        public static DeliveryList NewDeliveryList()
        {
            return new DeliveryList();
        }

        public DeliveryList()
        {
            // must have parameter-less constructor
        }

        public static DeliveryList GetDeliveryList()
        {
            return DataPortal.Fetch<DeliveryList>(new Criteria());
        }
        public static DeliveryList GetDeliveryList(int UserID)
        {
            return DataPortal.Fetch<DeliveryList>(new Criteria() { UserID = UserID });
        }
        public static DeliveryList GetDeliveryList(int? ProductID)
        {
            return DataPortal.Fetch<DeliveryList>(new Criteria() { ProductID = ProductID });
        }
        public static DeliveryList GetDeliveryList1(int? DeliveryTypeID)
        {
            return DataPortal.Fetch<DeliveryList>(new Criteria() { DeliveryTypeID = DeliveryTypeID });
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Delivery.GetDelivery(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getDeliveryList";
                        cm.Parameters.AddWithValue("@UserID", Singular.Security.Security.CurrentIdentity.UserID);
                        cm.Parameters.AddWithValue("@ProductID", Singular.Misc.NothingDBNull(crit.ProductID));
                        cm.Parameters.AddWithValue("@DeliveryTypeID", Singular.Misc.NothingDBNull(crit.DeliveryTypeID));
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}