// Generated 16 Nov 2021 11:23 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Products
{
    [Serializable]
    public class DeliveryType
     : SingularBusinessBase<DeliveryType>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> DeliveryTypeIDProperty = RegisterProperty<int>(c => c.DeliveryTypeID, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int DeliveryTypeID
        {
            get { return GetProperty(DeliveryTypeIDProperty); }
        }

        public static PropertyInfo<String> DeliiveryTypeProperty = RegisterProperty<String>(c => c.DeliiveryType, "Deliivery Type", "");
        /// <summary>
        /// Gets and sets the Deliivery Type value
        /// </summary>
        [Display(Name = "Deliivery Type", Description = ""),
        StringLength(50, ErrorMessage = "Deliivery Type cannot be more than 50 characters")]
        public String DeliiveryType
        {
            get { return GetProperty(DeliiveryTypeProperty); }
            set { SetProperty(DeliiveryTypeProperty, value); }
        }

        public static PropertyInfo<Boolean> IsActiveIndProperty = RegisterProperty<Boolean>(c => c.IsActiveInd, "Is Active", false);
        /// <summary>
        /// Gets and sets the Is Active value
        /// </summary>
        [Display(Name = "Is Active", Description = ""),
        Required(ErrorMessage = "Is Active required")]
        public Boolean IsActiveInd
        {
            get { return GetProperty(IsActiveIndProperty); }
            set { SetProperty(IsActiveIndProperty, value); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(DeliveryTypeIDProperty);
        }

        public override string ToString()
        {
            if (this.DeliiveryType.Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "Delivery Type");
                }
                else
                {
                    return String.Format("Blank {0}", "Delivery Type");
                }
            }
            else
            {
                return this.DeliiveryType;
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewDeliveryType() method.
        }

        public static DeliveryType NewDeliveryType()
        {
            return DataPortal.CreateChild<DeliveryType>();
        }

        public DeliveryType()
        {
            MarkAsChild();
        }

        internal static DeliveryType GetDeliveryType(SafeDataReader dr)
        {
            var d = new DeliveryType();
            d.Fetch(dr);
            return d;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(DeliveryTypeIDProperty, sdr.GetInt32(i++));
                LoadProperty(DeliiveryTypeProperty, sdr.GetString(i++));
                LoadProperty(IsActiveIndProperty, sdr.GetBoolean(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            AddPrimaryKeyParam(cm, DeliveryTypeIDProperty);

            cm.Parameters.AddWithValue("@DeliiveryType", GetProperty(DeliiveryTypeProperty));
            cm.Parameters.AddWithValue("@IsActiveInd", GetProperty(IsActiveIndProperty));

            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(DeliveryTypeIDProperty, scm.Parameters["@DeliveryTypeID"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@DeliveryTypeID", GetProperty(DeliveryTypeIDProperty));
        }

        #endregion

    }

}