// Generated 29 Oct 2021 15:45 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Products
{
    [Serializable]
    public class ProductList
     : SingularBusinessListBase<ProductList, Product>
    {
        #region " Business Methods "

        public Product GetItem(int ProductID)
        {
            foreach (Product child in this)
            {
                if (child.ProductID == ProductID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Products";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public int? ROSubCategoryID;
            public bool? isActiveInd;
            public Criteria()
            {
            }

            public Criteria(int ROSubCategoryID)
            {
                this.ROSubCategoryID = ROSubCategoryID;
            }

        }

        public static ProductList NewProductList()
        {
            return new ProductList();
        }

        public ProductList()
        {
            // must have parameter-less constructor
        }

        public static ProductList GetProductList()
        {
            return DataPortal.Fetch<ProductList>(new Criteria());
        }
        public static ProductList GetProductList(int? ROSubCategoryID)
        {
            return DataPortal.Fetch<ProductList>(new Criteria { ROSubCategoryID = ROSubCategoryID });
        }
        public static ProductList GetProductList(int? ROSubCategoryID, bool IsActiveInd)
        {
            return DataPortal.Fetch<ProductList>(new Criteria { ROSubCategoryID = ROSubCategoryID, isActiveInd = IsActiveInd });
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Product.GetProduct(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductList";

                        cm.Parameters.AddWithValue("@SubCategoryID", Singular.Misc.NothingDBNull(crit.ROSubCategoryID));
                        cm.Parameters.AddWithValue("@IsActiveInd", Singular.Misc.NothingDBNull(crit.isActiveInd));
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}